language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r web/requirements.txt
  - pip install -r executor/requirements.txt
  - pip install coveralls
# command to run tests
script: make coverage
after_success:
  - coveralls