version: '3'

services:
  db:
    image: postgres:9
    environment:
      POSTGRES_PASSWORD: opensubmit
      POSTGRES_USER: opensubmit
      POSTGRES_DB: opensubmit
    volumes:
      - postgres-volume:/var/lib/postgresql/data  
  web:
    image: troeger/opensubmit-web:0.7.21
    environment:
      OPENSUBMIT_DEBUG: "False"
      OPENSUBMIT_SERVER_URL: http://${external_adr}
      OPENSUBMIT_SERVER_HOSTALIASES: ${external_ip},web
      OPENSUBMIT_SERVER_MEDIAROOT: /data/media/ 
      OPENSUBMIT_DATABASE_NAME: opensubmit 
      OPENSUBMIT_DATABASE_USER: opensubmit 
      OPENSUBMIT_DATABASE_PASSWORD: opensubmit 
      OPENSUBMIT_DATABASE_HOST: db 
      OPENSUBMIT_DATABASE_ENGINE: postgresql      
      OPENSUBMIT_LOGIN_GOOGLE_OAUTH_KEY: ${google_oauth_key}
      OPENSUBMIT_LOGIN_GOOGLE_OAUTH_SECRET: ${google_oauth_secret}
      OPENSUBMIT_LOGIN_TWITTER_OAUTH_KEY: ${twitter_oauth_key}
      OPENSUBMIT_LOGIN_TWITTER_OAUTH_SECRET: ${twitter_oauth_secret}
      OPENSUBMIT_LOGIN_GITHUB_OAUTH_KEY: ${github_oauth_key}
      OPENSUBMIT_LOGIN_GITHUB_OAUTH_SECRET: ${github_oauth_secret}
      OPENSUBMIT_LOGIN_DEMO: "True"
      OPENSUBMIT_ADMIN_NAME: ${admin_name}
      OPENSUBMIT_ADMIN_EMAIL: ${admin_email}
      OPENSUBMIT_ADMIN_ADDRESS: ${admin_address}

    tty: true
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - data-volume:/data
  exec:
    image: troeger/opensubmit-exec:0.7.21
    environment:
      OPENSUBMIT_SERVER_HOST: http://web
    tty: true
    depends_on:
      - web

volumes:
  data-volume:
  postgres-volume:
