apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensubmit-exec
  labels:
    app.kubernetes.io/name: opensubmit
    app.kubernetes.io/component: exec
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: opensubmit
      app.kubernetes.io/component: exec
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opensubmit
        app.kubernetes.io/component: exec
    spec:
      containers:
      - name: opensubmit-exec
        image: troeger/opensubmit-exec:0.7.31
        envFrom:
        - configMapRef:
            name: opensubmit-config
