apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: opensubmit
  labels:
    app.kubernetes.io/name: opensubmit
    app.kubernetes.io/component: web
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 10g
spec:
  tls:
  - secretName: opensubmit-web-tls
    hosts:
    - beuth.open-submit.org
  rules:
  - host: beuth.open-submit.org
    http:
      paths:
      - path:
        backend:
          serviceName: opensubmit-web
          servicePort: 80
