apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensubmit-web-pv-claim
  labels:
    app.kubernetes.io/name: opensubmit
    app.kubernetes.io/component: web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensubmit-web
  labels:
    app.kubernetes.io/name: opensubmit
    app.kubernetes.io/component: web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: opensubmit
      app.kubernetes.io/component: web
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opensubmit
        app.kubernetes.io/component: web
    spec:
      containers:
      - name: opensubmit-web
        image: troeger/opensubmit-web:0.7.15
        ports:
        - containerPort: 80
        env:
        - name: OPENSUBMIT_SERVER_HOSTALIASES 
          value: "web"
        - name: OPENSUBMIT_SERVER_MEDIAROOT 
          value: "/data/media/"
        - name: OPENSUBMIT_DATABASE_NAME 
          value: "opensubmit"
        - name: OPENSUBMIT_DATABASE_USER 
          value: "opensubmit"
        - name: OPENSUBMIT_DATABASE_PASSWORD 
          value: "opensubmit"
        - name: OPENSUBMIT_DATABASE_HOST 
          value: "opensubmit-db"
        - name: OPENSUBMIT_DATABASE_ENGINE 
          value: "postgresql"
        envFrom:
        - configMapRef:
            name: opensubmit-config
        volumeMounts:
        - name: opensubmit-web-storage
          mountPath: /data

      volumes:
      - name: opensubmit-web-storage
        persistentVolumeClaim:
          claimName: opensubmit-web-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: opensubmit-web
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app.kubernetes.io/name: opensubmit
    app.kubernetes.io/component: web
